### ISSUE TITLE
Review/Change of Table Styles/Colors

### ISSUE THREAD

**Issue by jjames521** [Enterprise-CMCS/eAPD#2150]
This spins off of #1937 

#2218 is a spin off of this ticket, with a focus on one particularly complicated table.

Current tables are featuring yellow FFF1D2 which is same as pop up alert message

Suggested colors currently are 323A45 Dark Grey as bottom color and f1f1f1 light grey as sub category color (example subtotal)

Hierarchy and spacing issues need to be addressed

**Current**
<img width="1068" alt="Screen Shot 2020-04-01 at 11 13 00 AM" src="https://user-images.githubusercontent.com/62292793/78154807-b0a01e80-740a-11ea-90da-46cd65eaf38b.png">

**Idea for new colors**
<img width="421" alt="Screen Shot 2020-04-01 at 11 21 05 AM" src="https://user-images.githubusercontent.com/62292793/78154987-e6dd9e00-740a-11ea-9fbe-1b84af5eb185.png">

### This task is done when...
 - [ ] Agree on colors and change them
 - [ ] Agree and change styles globally

**Comment by jeromeleecms** [comment]
Let's get this into the sprint so we can be ready to talk to the design system folks on Monday. If we need to break this down into smaller tasks, please do so (i.e. doing some research about how we implemented this design system vs. the entire overall of the tables).

**Comment by jjames521** [comment]
This is my thought on a hierarchy change for colors, adding in the extra bonus of accessibility standards while being more light weight for development times and global changes to the tables.

Based on previous conversations we had about grey scale and the fact that the current standing yellow is our warning message in the CMS Design System

@beparticular @lauraponce 

![StateCostsSummaryColorChange.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/14e429cc-64cc-46fa-a81a-c8a6e2c0463b)

**Comment by jjames521** [comment]
@lauraponce @beparticular 

All the table variants and the value/color changes

![StateCostsSummaryNewValues.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/856a53a2-9bca-40f9-8362-3929f36849ae)

![Results of Previous Activities.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/a51494d6-5079-4b65-bd79-c14edc828699)

![Estimated Quarterly Incentive Payments.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/60607389-5cfb-4ed1-97bf-46d0ed0e1cca)

![Estimated Quarterly Incentive Payments2.png](https://images.zenhubusercontent.com/5e7151677c78c820a2a11970/1a7a12ae-2110-4d40-9bd9-b666928891f0)

**Comment by jjames521** [comment]
@beparticular Alright changes have been made to the Estimated Quarterly Incentive Payments

**Comment by akuas** [comment]
@jeromeleecms I think we can close this ticket because the changes have become obsolete and we have already done table redesign with [3380](https://app.zenhub.com/workspaces/cms-eapd-5a3823ad3659e94d8ee569be/issues/gh/enterprise-cmcs/eapd/3380)
@SGilliamA1M for awareness

**Comment by jeromeleecms** [comment]
Sounds good.
