### ISSUE TITLE
Show the Current FFY and 2 years before it in Results of Previous Activities

### ISSUE THREAD

**Issue by beparticular** [Enterprise-CMCS/eAPD#2439]
In DE's recent experience, they offered a suggestion based on their experience updating. 
The Results of Previous Activities > Actual Expenditures section does not update for the most relevant prior 3 years when the FFYs are selected. It seems that 2017, 2018 and 2019 always show.

(as noted below in the comments, these two screenshots are actually unrelated.) 
When FFYs 2021 and 2022 are selected in Program Summary > Program Overview, we would expect to see Results of Previous Activities show FFYs 2018, 2019 and 2020, but that is not what is currently provided on the page.

**Current Program Overview:**
![image](https://user-images.githubusercontent.com/45497254/89929832-cce17280-dbd7-11ea-8b23-e23008e9e883.png)

**Current Actual Expenditures:**
![image](https://user-images.githubusercontent.com/45497254/89929982-00240180-dbd8-11ea-90c8-9260dbca05cb.png)

**Results: 2020 is unaccounted for.**

Also noted by Jerome
"I was under the impression that it was not hard coded but it took the most recent year and subtracted three (the idea of an approval may have covered 3 years). It makes sense to include current year as well."

### This task is done when...
 - [x] The bug/feature expected behaviors as coded now have been clearly determined
 - [x] Decisions have been made on what years should be shown and how
 - [ ] The table is changed to show the Current Fiscal year and the two years before it.

**Comment by beparticular** [comment]
@thetif switching this to a dev ticket since there isn't any design work that needs to be done. 

The decision/regulation is that the table should show the Current Fiscal year and the two years before it. (Currently it is showing 3 years before the current fiscal, but not the current year). So in this case above it should show 2020, 2019 and 2018.

The Actual Expenditures table years are unrelated to the years chosen in the Program Summary, but noting there is a potential perception for the two to be related. Will keep an eye on that.

**Comment by thetif** [comment]
resolved in previous tickets
