### ISSUE TITLE
Review assurances and compliance for MMIS IAPD (V1)

### ISSUE THREAD

**Issue by beparticular** [Enterprise-CMCS/eAPD#2983]
Review the assurances and compliances page for MES Expansion -  make sure that the right regulations are referenced for MES. 

We also need to remove any specific HITECH references which do no apply to MMIS.

### This task is done when...
 - [ ] Determine - are the regs correct for MES ?
 - [ ] If not, create an issue to explore or show what needs to be changed
 - [ ] Determine - any branching between MMIS and E&E?
 - [ ] Determine - any branching between FFP selections?

**Comment by jeromeleecms** [comment]
Let's use the E&E template to establish the required Assurances and Compliances: 

![image.png](https://images.zenhubusercontent.com/5c547884d11206601037f0c7/9803c8ac-39ed-4943-8044-45477c2f75e3)

This is the OMB required E&E template last approved 05/20/2021

**Comment by SGilliamA1M** [comment]
@jeromeleecms and @stephanieboydcms - the [Assurances and Compliance](https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=1383%3A12345&t=Rn8u9FYuQpsrRjvJ-1) updates are Ready for Review. 

**Open Question:**
Do we have a reference point that users will navigate to when they click ea. CFR?

**Comment by jeromeleecms** [comment]
Yes - I can provide links for those that don't exist.

Also, this totally slipped past me 45 CFR 92.36 was moved to 45 CFR 75.326. The link was corrected in HITECH, but didn't make it into the most recent version template of the E&E APD. Please replace that reference with the correct one. 

Everything else looks good! Also, thanks for including the export view explicitly.

**Comment by jeromeleecms** [comment]
After today's Design Sync, is there any additional items we need to address or is this ready to pass on to Dev?

**Comment by SGilliamA1M** [comment]
@jeromeleecms - one additional change has been applied in the Export View to reflect the display of "Yes" and "No" display. Other than that, this ticket is ready to pass on to Dev. Thank!

**Comment by jeromeleecms** [comment]
Reviewing Dev ticket + Acceptance criteria. This looks good to close out.
