### ISSUE TITLE
Remove funding source from Activity Name in Activity List for MMIS and E&E

### ISSUE THREAD

**Issue by beparticular** [Enterprise-CMCS/eAPD#2985]
With the MES expansion, we will not need to show the funding source in parenthesis on the Activity List since the funding source will be the same for all activities within an APD. 
For all APDs after HITECH, this will need to be the case. 

![Screen Shot 2021-03-19 at 4.48.08 PM.png](https://images.zenhubusercontent.com/591f3b9351aa2c30577ecf92/c5480414-6e04-4f06-951f-13ec04e80709)

### This task is done when...
 - [ ] The funding source is removed from the activity title on MES APDs
 - [ ] The funding source still shows on the activity title on HITECH APDs

**Comment by thetif** [comment]
covered in dev ticket #3493
