### ISSUE TITLE
[Design Issue] Add FFY end date to the FFY help text

### ISSUE THREAD

**Issue by beparticular** [Enterprise-CMCS/eAPD#3454]
This is important before Oct 1 this year!

Question asked at the MESC feedback session. 
”When would a specific FFY check box (example FFY 2021) drop off the options with an APD submission?” 
The answer is October 1, 2021, or October 1 of whatever fiscal year is ending.

Questions that need to be answered for forthcoming dev issue  -   
Is this for newly created APDs only? 
What happens to APDs that exist in the system but aren’t yet locked down? 
We also need to start thinking about what the FFY roll over means for locking down an APD as the document of record. What does it mean for historical data.

### This task is done when…

- [x] designs are created, taking into consideration multiple FFY, multiple entries, long entries, weird entries, validation, and/or the export view if applicable
- [x] 508 considerations and/or recommendations are reviewed
- [x] designs are shared
- [x] designs are approved by product

**Comment by beparticular** [comment]
@thetif FYI per Jerome 

If we have no active APDs on Oct 1, we don't have to hit that timeline. We may want to spin up some fake APDs in staging though to see what happens during the transition. If the FFY 2021 disappears, we will have to evaluate how to make sure the FFY 2021 stays present if it was originally authored with FFY 2021. Lock down on submit may help with that, but we wouldn't users to forget to lock it down, go through a FFY and then be unable to recover that FFY 2021 content/data

**Comment by beparticular** [comment]
Currently in prod - There are 3 APDs, 2 without years
Currently DE is the only active APD with 2021 FFY selected. Should we just reach out to her to let her know what will happen, and make any other decisions about help text after we decide what to do on lock down?  @jeromeleecms @CSwartzHMA 

How it works - When Oct 1 rolls around, the previous FFY chosen, will remain in the APD and the fields can be edited, but the FFY will not be shown here. You can unselect the previous FFY.

**Comment by CSwartzHMA** [comment]
@beparticular Are there other FFYs selected in the DE APD?

**Comment by beparticular** [comment]
@CSwartzHMA they don't in that APD, but they do have a more recent APD from 2020 in their account.

**Comment by SGilliamA1M** [comment]
@thetif - would you mind confirming the following:

- For existing APDs that have previous federal fiscal years selected, does the system show the selected federal fiscal years instead of hiding them?

**Comment by SGilliamA1M** [comment]
Awesome, thanks @thetif! @jeromeleecms this ticket is good to close out :)

**Comment by jeromeleecms** [comment]
This has already been addressed and no further action is needed.
