### ISSUE TITLE
[Feature] Update Activities Dashboard

### ISSUE THREAD

**Issue by thetif** [Enterprise-CMCS/eAPD#3493]
**Description and related issues -**

**For MMIS add an example box that says**

"Examples of individual activities include but are not limited to: E&E online application, E&E worker portal, E&E noticing system, claims processing engine, claims processing prior authorization, claims processing record keeping, HIE interface(s), CQM databases, decision support systems analytics platform, provider enrollment screening, provider fraud/waste/abuse, managed care member enrollment, etc. For each activity added, you will have the opportunity to provide details in their own respective subsections."

![Screen Shot 2021-09-27 at 2.44.07 PM.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/91d357c7-da2e-4f60-ae14-f431c4ac9278)

**For MMIS remove funding source name from Activity List**

![image.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/341015de-a066-4543-b919-de21f1247c8f)

** Display error message for no activities when admin check on**

If there are no activities and admin check is on, then this message should be displayed above the Add activity button, should have been handled in #3349

![image.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/fa22ffa2-b34c-481f-90db-38b6cbe25889)

Figma: https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=41:5864&t=GKsE3Y4JOR7FbJTU-0

### This task is done when…
- [ ] for MMIS add example text
- [ ] for MMIS remove funding source from activity name
- [ ] show empty activity message when admin check is on
- [ ] empty activity messages shows in Admin Check panel
- [ ] clicking the empty activity message in the Admin Check panel takes you to the Activities Dashboard

**Comment by beparticular** [comment]
Note - #4050 has been added for content review of example boxes

**Comment by beparticular** [comment]
@jeromeleecms can you review this to make sure that the language is appropriate for MMIS iAPD (the initial examples reference E&E)

**Comment by mirano-darren** [comment]
Also adding to this ticket
- Add unit tests for the Security Planning page
