### ISSUE TITLE
User Research: Beta Test "slim" MMIS IAPD

### ISSUE THREAD

**Issue by beparticular** [Enterprise-CMCS/eAPD#3552]
Implementing feature flags(?) would enable us to have a small subset of users to test out the slimmed down version of an MMIS IAPD. Research would focus on getting users to complete a MMIS IAPD in the system.

Related Mural to document fields needed
https://app.mural.co/t/cmsmural6360/m/cmsmural6360/1595447949758/6772a44673aeee1c6ea68587eaf7783922e7aa7a?sender=4ec24376-646b-448f-a73f-31a20df36be5

### This task is done when...

- [ ] criteria 1
- [ ] criteria 2

**Comment by jeromeleecms** [comment]
Closing this in favor of #2456
