### ISSUE TITLE
[Design issue] Review/update help text for MMIS expansion

### ISSUE THREAD

**Issue by aricka-lewis** [Enterprise-CMCS/eAPD#3690]
We need to review the help text in the system to make sure it is all relevant to MMIS.

Considerations:
- Review help text from the prototype from the MES Expansion research
- Add the outcomes repository link to the Outcomes and Metrics help text
- Update the outcomes examples to better represent MMIS

### This task is done when...

- [x] all help text has been reviewed and changes documented
- [x] help text is updated in the design
- [x] 508 considerations and/or recommendations are reviewed
- [x] designs are shared
- [x] designs are approved by product
---

Add additional labels (design, dev, compliance, BUG, etc) and size before submitting.

If the issue is needed to complete prioritized work for the CURRENT SPRINT, add it to the "This Sprint" pipeline. Otherwise, all other issues will be automatically added to the _unprioritized pipeline_ for prioritization in backlog refinement or sprint planning with Product.

**Comment by aricka-lewis** [comment]
@akuas Will you share the link to the prototype used in the MES Expansion research?

**Comment by akuas** [comment]
@aricka-lewis for awareness
[Create a New APD ](https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=6601%3A41641)
[APD Overview](https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=7162%3A43951)
[Activities Dashboard](https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=0%3A12587)
[Activity Overview (formerly Program Summary)](https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=2522%3A1042)
[Analysis of Alternatives and Risks](https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=3440%3A5119)
[Activity Schedule and Milestones](https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=7162%3A43950)
[Conditions for Enhanced Funding](https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=7162%3A43949)

**Comment by akuas** [comment]
Below is our research recap notes with all the designs consolidated, as well. 
https://app.mural.co/t/cmsmural6360/m/cmsmural6360/1595447960277/2d7cd44401a2d21d24c405c01851fc788ad9a25f?sender=a0a6af81-670e-4528-b527-cb95df232a7c

**Comment by akuas** [comment]
Current plan is to list out side by side the differences between old MMIS help text and new MMIS help text, as well as some help text that need to be changed because they are hitech specific. This list could be housed on a google doc. Then we will go through figma page by page and update the designs. Since it is a content change and not a drastic design/flow change I don't think we need to duplicate the designs and put the old help text beside the new help text on figma.

**Comment by akuas** [comment]
After speaking with Jerome, I agree it would be best to not have the State Priorities and Scope of APD in the Executive Summary. The reason being it can be several pages long typically to answer those questions and it does not answer the question of "Why does this APD exist?" for a reviewer. So, the scope of this ticket could just be the decision to not add this section.

**Comment by akuas** [comment]
Note for myself:
1. Need to make mmis specific help text for cost allocation and other funding

**Comment by akuas** [comment]
@jeromeleecms Below is the my list of outstanding copy changes. It is titled outstanding MMIS help text changes on the bottom right of the page. Let me know if I have missed any. In the meantime, I will start changing the designs. Also, you use have copy recommendations, you can either put a sticky beside the table of enter it into the table.
https://app.mural.co/t/ccs9461/m/cmsmural6360/1611780005309/48a85b47f678d3fd5858070e25da7025d2da0a09?sender=u78eaeef0ed599cf016d95977

**Comment by jeromeleecms** [comment]
Made comments by the proposed copy. Will review the copy directly in the app tomorrow AM. @stephanieboydcms did you want to take a look as well?

**Comment by stephanieboydcms** [comment]
Thank you Akua!  One minor comment.

**Comment by akuas** [comment]
Thanks @jeromeleecms and @stephanieboydcms . I will apply these changes.

**Comment by akuas** [comment]
Closing Notes
Cost Allocation and Other Funding Changes
1. Change the 2nd line in copy
> CMS will work with states individually to determine the most appropriate cost allocation methodology.
Cost allocation formulas should be based on direct benefit to Medicaid.
Cost allocation must account for other available federal funding sources including division of resources and activities across relevant payers, and relative benefit to the state Medicaid program.
Cost allocations should be current and ensure financial participation of all parties so Medicaid funds are neither the sole contributor at the onset, nor the primary source of funding. Other payers who may benefit must contribute their share from the outset. The absence of ancillary payers is not sufficient cause for Medicaid to be the primary payer.

**Comment by akuas** [comment]
@SGilliamA1M @stephanieboydcms @jeromeleecms I made the changes to the designs based on the recommendation on Mural. If there are no objections/additional recommendations, I think this is ready to move to dev.

**Comment by akuas** [comment]
@jeromeleecms I have added the Budget and FFP page designs and annotation to this ticket

**Comment by stephanieboydcms** [comment]
Reviewed complete with a few VERY minor edits.  Great job @akuas

**Comment by akuas** [comment]
@stephanieboydcms Thanks, I made those changes.

**Comment by jeromeleecms** [comment]
Looks good - since these are text changes, I'll pass these along to Dev for ticket creation.

**Comment by thetif** [comment]
@akuas @jeromeleecms is this for HITECH and MMIS or only MMIS?

**Comment by akuas** [comment]
@thetif This is only for MMIS.

**Comment by thetif** [comment]
Thanks Akua! Dev tickets #4500, #4602

**Comment by stephanieboydcms** [comment]
No additional edits!

**Comment by jeromeleecms** [comment]
Dev Tickets done. In progress, but this is done.
