### ISSUE TITLE
Level 1 ITSI Monitoring

### ISSUE THREAD

**Issue by cthulhuplus** [Enterprise-CMCS/eAPD#3956]
## From ITSI team

Discovery - ***Minimal*** ADO involvement

1. Application Discovery
	a. Architectural Diagram - ***ADO needs to provide***  
	As part of discovery, we would in general go thru ADOs arch or logical diagram to list all the infrastructure pieces and create a template and then engage ADOs to go over discovery and add application logs to the mix to assess the application health.

2. Data Discovery
	a. Determine which kind of data is getting indexed
	b. Determine deltas, without engaging the application team
		i. Put in a ticket to Splunk team

3. ITSI Service Analyzer Tree Initiation based on Architectural Diagram

Integration - **(1-2 Weeks) ADO Involvement Is Needed**

1. Application Team Engagement - 1 Day
	a. Setup Initial Decomp Call
	b. Decomp Call - 1hr
		i. Logs
			1. AWS Cloudwatch Metrics Data
			2. ADO application Log Data
			3. Capture Deltas
		ii. Thresholds
			1. Available in ITSI Templates
		iii. Alerting
		iv. Email Distro Lists

2. Level 1 - ITSI Service Analyzer Tree Finalization
	a. Address Deltas - 1 week - All Environments - 1hr a day
		i. Application team
		ii. Splunk team
	b. KPI’s
	c. Thresholding

3. Service layer - 1 week
	a. Back and forth with Application team
	b. Application team approval

4. EMM Integration - 2 days (Dependent on EMM Sprint Planning)

### This task is done when...

- [ ] created Architectural Diagram
- [ ] finished working with ITSI on list above

**Comment by jeromeleecms** [comment]
Closing this until we hear back from the requested group.

**Comment by jeromeleecms** [comment]
Finally heard back from the ITSI folks - reopening this for @thetif

**Comment by jeromeleecms** [comment]
Nothing to take action on - waiting for ITSI folks for guidance. Closing this until then.
