### ISSUE TITLE
[Maintenance] Copy Dio's new APDs out of staging

### ISSUE THREAD

**Issue by thetif** [Enterprise-CMCS/eAPD#4172]
### Description and related issues
Copy Dio's new APDs out of staging

### This task is done when…

- [ ] Dio's apds are stored in source control
- [ ] Update FFYs

**Comment by jeromeleecms** [comment]
Can we document what the seed contains in the Wiki somewhere? 

Dio provided what each APD contains here: https://docs.google.com/document/d/1ZaSZK7fEUyA7QiJdJPttmMMUjB3J0Tco/edit

**Comment by thetif** [comment]
I copied the APD json into the branch I'm currently working on, so that is saved, I'll make a wiki page that combines all this info, but we should probably wait until the budget info is in the APD so that we have the whole object.

**Comment by jeromeleecms** [comment]
Pending integration work with Backend budget changes.

**Comment by jeromeleecms** [comment]
Closing this out so Darren can make improved versions of APDs
