### ISSUE TITLE
[Bug] Issue when entering numbers into Estimated Quarterly Expenditure table

### ISSUE THREAD

**Issue by tbolt** [Enterprise-CMCS/eAPD#4183]
Some numbers (I tried 29 and 888 as examples) change the input values (# shown in the field, not necessarily what is saved in the database).

See the video below

### This task is done when...

- [x] bug investigated further to determine root cause
- [x] bug resolved

---

https://images.zenhubusercontent.com/113234315/63a2ef2c-8b03-42d1-b807-87b09e3868fb/numberbug.mov

**Comment by Sun-Mountain** [comment]
@tbolt what browser(s) did you use for this bug so I know what to try when I try to replicate this.

**Comment by tbolt** [comment]
@Sun-Mountain Chromium

**Comment by jeromeleecms** [comment]
Just documenting this from standup today - we may have to evaluate priority for this if turns out to be isolated + heavy lift to fix as table/field as this is going away when we shift our efforts to MMIS.
