### ISSUE TITLE
[Design Issue] Add a field to collect data on disaster recovery plan 

### ISSUE THREAD

**Issue by beparticular** [Enterprise-CMCS/eAPD#4221]
Add a field or fields to collect data on disaster recovery plan as per these regulations: 

45 cfr 95.610: A statement setting forth the security and interface requirements to be employed and the system failure and disaster recovery/business continuity procedures available or to be implemented; and

SECTION XII: SECURITY, INTERFACE, DISASTER RECOVERY, AND BUSINESS CONTINUITY PLANNING
The state should implement or maintain a comprehensive Security and Interface Plan for IT systems and installations involved in the administration of the Medicaid Program. The state should describe what is included in this Plan. Examples include site and facility security, security of data communications equipment, and security of personal health information (PHI) as required by Health Information Patient Access Act (HIPAA).
The state should maintain a Business Continuity and Disaster Recovery Plan throughout the work to be completed. The state should describe what is included in this Plan. Examples include a contingency plan, a list of key personnel to be contacted in the event of an emergency, and maintenance of a complete set of backup programs and related system documentation that will be stored off-site to be used in an emergency.

https://www.ecfr.gov/current/title-45/subtitle-A/subchapter-A/part-95/subpart-F/subject-group-ECFR8ea7e78ba47a262/section-95.610

### This task is done when…
- [x] Determine where this field(s) needs to live
- [x] Chose a label for the field(s)
- [x] Write the instructions/help content for this field(s)
- [x] designs are created, taking into consideration validation, multiple FFY, multiple entries, long entries, weird entries, and/or the export view if applicable
- [x] 508 visual, content, and UX considerations and/or recommendations are reviewed
- [x] designs are shared
- [x] designs are approved by product
- [x] if there is a long discussion, a summary of changes for dev will be added to the last comment before transfer
- [x] a list of changes to be made if this is improving an existing feature

**Comment by SGilliamA1M** [comment]
**NEW Designs have been created for the: [Security Planning]**(https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=1974%3A14945) pg

- Left Navigation bar updated to include: Security Planning
- Page includes two **required** sections: 
     1) **Security and Interface Plan** - One text field (Rich Text Editor)
     2) **Business Continuity and Disaster Recovery Plan** - One text field (Rich Text Editor)
- Example boxes appear per section
- Admin Check when turned ON, will validate rich text fields

@jeromeleecms - please provide final review/comments at your convenience, thanks!

**Comment by SGilliamA1M** [comment]
@thetif - please provide final review/comments at your convenience, thanks!

**Comment by jeromeleecms** [comment]
Made a proposed content update for the help text in the Figma. If it makes sense, we can model the language for the second field and remove the example text.

**Comment by SGilliamA1M** [comment]
@jeromeleecms appreciate the review and feedback on the suggested changes. The following has been modified:

**- Removed example text box from both sections (Security and Interface Plan; Business Continuity and Disaster Recovery Plan)
- Updated help text for: Security and Interface Plan; Business Continuity and Disaster Recovery Plan**

**Comment by jeromeleecms** [comment]
Just checking in on this - the revised help text and validation text looks great. Anything we need to do before transitioning this to dev @SGilliamA1M ?

**Comment by SGilliamA1M** [comment]
Thanks @jeromeleecms! Designs are ready to transition to Dev.

**Comment by thetif** [comment]
created dev ticket #4431
