### ISSUE TITLE
[Feature] Update FFP field for MMIS IAPDs

### ISSUE THREAD

**Issue by mirano-darren** [Enterprise-CMCS/eAPD#4226]
### Description and related issues
With the addition of MMIS APD implementation we are going to update the FFP field. This may eventually move to Activity Overview, so it is preferable to create a reusable component for it. 

Updated FFP field:
![image.png](https://images.zenhubusercontent.com/60e5e61f47c95c0dd8ed87be/a5daec22-2b8a-48c1-8462-9c3e94efdd2f)

Updated FFP Field w/ validation errors:
![image.png](https://images.zenhubusercontent.com/60e5e61f47c95c0dd8ed87be/24be31d4-483a-4f68-a398-e087a91f5eb9)

### Mockups or link to Figma

- [Design ticket](https://github.com/CMSgov/eAPD/issues/3688)
- [Figma link](https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=601%3A12578&t=YzEmzn06igRFHQYB-1)

### Behind the scene changes
 - update the apdActivity model
 - create actions on the frontend to create the appropriate patch for the backend

**Feature flags-**
enableMMIS

### Acceptance criteria

- [ ] For MMIS, update FFP to look like the design
- [ ] Update the apdActivity model to store the selection of DDI or M&O
  - [ ] 90/10 is always DDI
  - [ ] 75/25 can be DDI or M&O
  - [ ] 50/50 can be DDI or M&O
- [ ] error messages should show up in AdminCheck
- [ ] clicking the error message should take you to the Budget and FFP page
- [ ] create a migration to convert existing APDs

### Testing criteria

| Given | When | Then | Covered |
| ----- | ---- | ---- | ------- |
|  a HITECH APD | the user navigates to Budget and FFP  | everything stays like it currently is | |
| a MMIS APD | the user navigates to Budget and FFP | the FFP selection looks like the figma | |
| a MMIS APD | the user selects an FFP type | the FFP type is added to the patch list in redux and autosaved | |
| a MMIS APD | the user opens an existing APD | the appropriate FFP type is selected | |

**Comment by beparticular** [comment]
@mirano-darren wanted to note on this one that the options after the FFP selection (DDI and Ops) also needs to be present for the 50/50 split, but not the 90/10.

**Comment by akuas** [comment]
The ffp will live in the [Budget and FFP](https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=2288%3A18869&t=vaPfgl20PqIUHBAE-1), at least for now. @mirano-darren @thetif

**Comment by thetif** [comment]
@jeromeleecms will this be for HITECH too or just MMIS?

**Comment by jeromeleecms** [comment]
This is just MMIS. We won't have M&O as part of HITECH.
