### ISSUE TITLE
[Accessibility] Hiding the add button when a subform is already open

### ISSUE THREAD

**Issue by mirano-darren** [Enterprise-CMCS/eAPD#4265]
Describe the task here and link or add dependencies to any applicable issues...

To prevent data loss, we disabled the ability to have multiple subforms open at once. We solved this issue by hiding the add button if a subform is already open. WAVE caught this functionality and marked it as an error because we are hiding the button, potentially adding issues to users that rely on screen readers. We should come up with another way to prevent multiple subforms being open, but without hiding the add button.

Potential solution. Instead of hiding the button, we can leave the button in and gray it out if a subform is already open. We could also add a tooltip on hover that states something along the lines of "Please finish the current form before adding a new X"

### This task is done when...

- [ ] WAVE finds no errors with this issue

**Comment by jeromeleecms** [comment]
Future note: Can we just remove the button instead of hiding it?
