### ISSUE TITLE
[Dev] Executive Summary with no activities for MMIS APDs

### ISSUE THREAD

**Issue by mirano-darren** [Enterprise-CMCS/eAPD#4307]
Describe the task here and link or add dependencies to any applicable issues...

MMIS APDs do not require activity 1 to be Program Administration and will no longer be automatically generated. Since a 0 activity MMIS APD is possible, we have to adapt the Executive Summary for that edge case. 

Original Design Ticket:  #3381

Figma: https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=587%3A10819 (Just this frame)

Test Cases: 
| Given  | When | Then |
| ------------- | ------------- | ------------- |
| A MMIS APD with no activities  | On the Executive Summary page and Executive Summary on the exported page  | Executive Summary should reflect no activities have been added. (See Figma link for language)  | 
| A MMIS APD with at least one activity  | On the Executive Summary page and Executive Summary on the exported page  | Executive summary should behave like normal and show a summary of the activity  | 

### This task is done when...

- [ ] Executive summary adapts to a zero activity MMIS APD

**Comment by thetif** [comment]
added to #4418
