### ISSUE TITLE
[Dev] MMIS - Add State Priorities and APD Scope to the Executive Summary

### ISSUE THREAD

**Issue by mirano-darren** [Enterprise-CMCS/eAPD#4309]
Describe the task here and link or add dependencies to any applicable issues...

For MMIS APDs, we are going to add the information in the State Priorities and APD Scope page to the Executive Summary.

Original Design Ticket: #4355

Figma: https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=598%3A11888

Test Cases:
| Given  | When | Then | 
| ------------- | ------------- | ------------- | 
| A MMIS APD  | On the Executive Summary page and Executive Summary on the exported page  | The State Priorities and APD Scope section should accurately reflect the information in the State Priorities and APD Scope page  | 
| A MMIS APD  | A change has been made to the State Priorities and APD Scope  | The State Priorities and APD Scope section in the executive summary should update to reflect the change | 

### This task is done when...

- [ ] State Priorities and APD Scope has been added to the Executive Summary
- [ ] State Priorities and APD Scope section in the Executive Summary adapts to changes made.

**Comment by thetif** [comment]
added to #4418
