### ISSUE TITLE
[Dev] Change submit email address based off of what APD funding type is selected

### ISSUE THREAD

**Issue by mirano-darren** [Enterprise-CMCS/eAPD#4312]
Describe the task here and link or add dependencies to any applicable issues...

The Export and Submit page allows the user to submit an APD via email. However there are different email addresses depending on the APD funding type. The Export and Submit page **should show the correct submit email address automatically.**

Original Design Ticket: https://app.zenhub.com/workspaces/cms-eapd-5a3823ad3659e94d8ee569be/issues/cmsgov/eapd/3691 (#3691)

Figma: https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=514%3A14637

Test Cases:
| Given  | When | Then |
| ------------- | ------------- | ------------- |
| A HITECH APD  | On the Export and Submit page  | Should show the email: MedicaidHITECH@cms.hhs.gov  |
| An MMIS APD  | On the Export and Submit page  | Should show the email: MedicaidMMIS@cms.hhs.gov  |

### This task is done when...

- [ ] Export and Submit page shows correct email for HITECH APDs
- [ ] Export and Submit page shows correct email for MMIS APDs

**Comment by thetif** [comment]
added to #4313
