### ISSUE TITLE
[Dev] APD name field validation in APD Overview and Create new APD pages

### ISSUE THREAD

**Issue by mirano-darren** [Enterprise-CMCS/eAPD#4337]
The current behavior of the APD name field does not allow the user to enter a blank name. On blur, if the field is blank, the name will default to "Untitled IAPD". So for validation on this field, check if the name matches this default name. 

Validation error message language: "Provide your own APD Name"

### This task is done when...

- [ ] admin check catches when an APD has the name "Untitled"
- [ ] APD name field in create new APD page has inline validation on blur when name defaults to "Untitled"

**Comment by thetif** [comment]
added to #4211
