### ISSUE TITLE
[Design Issue] Integrate State Priorities and Scope of APD into Executive Summary flow

### ISSUE THREAD

**Issue by akuas** [Enterprise-CMCS/eAPD#4355]
We need to decide whether we want to include the state priorities and scope of apd into the executive summary if so where. A possible recommendation is to start off with this section then flow down to activities

### This task is done when…

- [x] Create an executive summary design with state priorities and scope of apd
- [ ] designs are approved by product
- [ ] if there is a long discussion, a summary of changes for dev will be added
      to the last comment before transfer
- [ ] a list of changes to be made if this is improving an existing feature

---

**Comment by akuas** [comment]
For awareness @stephanieboydcms @SGilliamA1M After speaking with Jerome, I agree it would be best to not have the State Priorities and Scope of APD in the Executive Summary. The reason being it can be several pages long typically to answer those questions and it does not answer the question of "Why does this APD exist?" for a reviewer, which is the purpose of the Executive Summary. 


So, the scope of this ticket could just be the decision to not add this section. [4418](https://github.com/Enterprise-CMCS/eAPD/issues/4418) is the dev ticket to address the executive summary changes and that also includes the APD overview, so this ticket does not need to transfer to dev. @jeromeleecms With that being said, if there are no objections, I think this ticket is ready to close.

**Comment by SGilliamA1M** [comment]
Thanks @akuas! In reviewing this proposal further, I agree that it is best to leave the State Priorities and Scope of APD out of the Executive Summary. In addition, the Executive Summary appears to be more focused on summarizing Activities and funding request totals. The dynamic of what we're capturing here would shift if we added State Priorities and Scope of APD.

**Comment by jeromeleecms** [comment]
Closing this as we may need to have a different field to capture the executive summary (future enhancement).
