### ISSUE TITLE
[Dev] Update sidebar navigation and activity sections for MMIS APDs

### ISSUE THREAD

**Issue by mirano-darren** [Enterprise-CMCS/eAPD#4371]
Describe the task here and link or add dependencies to any applicable issues...

Updates to Nav Items:
- State Priorities and Scope of APD (only for MMIS)
- Activities
  - Analysis of Alternatives and Risks (only for MMIS)
  - Activity Schedule and Milestones // break out Activity Schedule from APD Overview and Milestones from Outcomes and Milestones (both HITECH and MMIS)
  - Conditions for Enhanced Funding (only for MMIS)
  - Outcomes and Metrics // rename from Outcomes and Milestones (for both HITECH and MMIS)
- Disaster Recovery Plan (only for MMIS)
- Remove Proposed Budget -> Quarterly Federal Share (mmis only)
- Remove Proposed Budget -> Estimated Quaterly Incentive Payments (mmis only)

Re-organize activity sections:
- Move Activity Schedule from Activity Overview to Activity Schedule and Milestones (for both HITECH and MMIS)
- Move Milestones from Outcomes and Milestones to Activity Schedule and Milestones (for both HITECH and MMIS)

Updates to admin check:
- Activity Schedule error should link to new location

Design ticket: #4357

Since some pages will be changing with MMIS APDs, we also need to update the sidebar navigation. 

[Figma](https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=1515%3A12934)
[List of MMIS Changes](https://docs.google.com/spreadsheets/d/1yCB-XfLO6QJL4iugFhoUHZWYJZ7IMtwBI8ZgtVilHmE/edit#gid=0)

Acceptance Criteria:
| Given  | When | Then |
| ------------- | ------------- | ------------- |
| Sidebar navigation  | interacting with the nav  | Each section/subsection should match the Figma  |
| Sidebar navigation  | clicking through the nav  | Key State Personnel, Results of Previous Activities, Activities, Proposed Budget, and Executive Summary sections should be expandable/collapsible   |
| Sidebar navigation  | clicking through the nav  | Each section/subsection should hyperlink to the correct page  |

### This task is done when...

- [ ] Sidebar navigation has been updated for MMIS
- [ ] APD sections have been re-arranged according to design

**Comment by tbolt** [comment]
11/17 - New Update Proposed budget sections based on latest designs here
https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=1992%3A16701
