### ISSUE TITLE
[Design Issue] Update example box copy on MMIS designs

### ISSUE THREAD

**Issue by akuas** [Enterprise-CMCS/eAPD#4381]
The purpose of this ticket is to update the designs of example boxes based on what was agreed upon in 4050. This ticket also would involve moving help text elsewhere in the section, if need be.
[Current Design of Example Boxes for HITECH](https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=1303%3A11957)
### This task is done when…

- [x] Update Key State Personnel example
- [x] Update Outcome and Metrics example
- [x] Update State Staff and Expenses example
- [x] Update Other State Expenses example
- [x] Update Cost Allocation: Cost Allocation Methodology and Other Funding Amount examples
- [x] Update Activities Dashboard example
- [x] Update Statement of Alternative Considerations example
- [x] designs are created, taking into consideration validation, multiple FFY,
      multiple entries, long entries, weird entries, and/or the export view if
      applicable
- [x] 508 visual, content, and UX considerations and/or recommendations are
      reviewed
- [x] designs are shared
- [x] designs are approved by product
- [x] if there is a long discussion, a summary of changes for dev will be added
      to the last comment before transfer
- [x] a list of changes to be made if this is improving an existing feature

---

Add additional labels (design, dev, compliance, BUG, etc) and size before
submitting.

If the issue is needed to complete prioritized work for the CURRENT SPRINT, add
it to the "This Sprint" pipeline. Otherwise, all other issues will be
automatically added to the _unprioritized pipeline_ for prioritization in
backlog refinement or sprint planning with Product.

**Comment by akuas** [comment]
Closing Notes as of January 20th 2023 (in progress)
1. HIE Overview: Removed 
2. Key Personnel and Program Management: "Examples: Project/Product Manager, Development Lead, Business Owner"
3. Statement of alternative considerations and supporting justification: Removed
4. Outcomes and Metrics:
> **CMS Required Outcome Example:**
> Outcome: A provider can initiate, save, and apply to be a Medicaid provider.
> Metrics:
>> Number of requests to help desk for problems with initiating, saving, and applying.
>> Average time to enroll from point of submit.
>> Total time to enroll all providers
>> Total # of enrolled providers

> " **State Specific Outcome Example**
> Outcome: Transform MHD from a transactional, request as needed data approach to a business intelligence driven model recognizing and treating data as an asset.
> Metrics:
>> 1. Conducting an initial data maturity analysis and prioritizing recommendations and review every two (2) years.
>> 2. Establishing a Data Governance Council who is engaged and meets at a minimum of quarterly and has at least >> 60% participation as measured by attendance.
To view other outcome and metrics examples, visit the [CMS Certification Repository](https://cmsgov.github.io/CMCS-DSG-DSS-Certification/) ."

5. State Staff : 
> "**Example:** Two Auditors, Class 1, working at 75% time = Auditor, Class 1 at 1.5 FTE
> **Example:** Two Auditors, Class 1 and Class 2, working at 75% time = Auditor, Class 1, 0.75 FTE and Auditor, Class 2, 0.75 FTE."

**Comment by akuas** [comment]
@jeromeleecms @SGilliamA1M @stephanieboydcms Can you please review this copy? Jerome wrote most of them.

**Comment by akuas** [comment]
@jeromeleecms I imagine this would come up, but do we expect dev to change the example box copy for HITECH as well, or should this be exclusive to MMIS. As I see it Outcomes and Metrics, Key Personnel, Activities Dashboard and Forseeeable Risks, have been edited to suit MMIS more.

**Comment by stephanieboydcms** [comment]
@akuas I just added one mention in regards to abbreviations and then two other minor edits on the Figma page.  Let me know if you have any questions.

**Comment by jeromeleecms** [comment]
My expectation would be HITECH would remain as is and we would have separate examples for MMIS (and eventually E&E). As we expand beyond IAPDs, we will have to revisit this as well to make some PAPD and OAPD examples.

**Comment by akuas** [comment]
@jeromeleecms Thanks, I will note that in the closing notes.

**Comment by akuas** [comment]
@stephanieboydcms Thanks for reviewing the example boxes, but I think you were looking at the old copy. The old copy was either implemented in the UI or was a previous design copy that was not implemented. The new copy is on the right titled suggested content. You can also view them page by page with the links in the closing notes.

**Comment by stephanieboydcms** [comment]
@akuas thank you for the assist!  The only comment I had was regarding date formats.  Some use "January 1, 2023" and some are 01/01/23.  I was not sure if there was a reason or we just need to pick one format for consistency purpose.  Looks really good Akua!

**Comment by jeromeleecms** [comment]
No other comments/questions - this is good by me.

**Comment by akuas** [comment]
@thetif @mirano-darren This ticket is ready for dev.

**Comment by thetif** [comment]
Created dev tickets
#4513 #4507 #4510 #4512 #4511 #4509 #4508

**Comment by thetif** [comment]
we don't need tests for this because it's just test changes so handing off to @jeromeleecms

**Comment by jeromeleecms** [comment]
Looks good. Closing this as done and ready for Dev.
