### ISSUE TITLE
Create New Priority Alerts Slack Channel

### ISSUE THREAD

**Issue by cthulhuplus** [Enterprise-CMCS/eAPD#4383]
To increase visibility of alerts that require action the eAPD team wants to create a new Slack channel for Priority Alerts. 

### This task is done when...

- [ ] New eAPD Slack channel for priority alerts has been created
- [ ] Follow on Issue is created to send alerts to the new Slack channel

**Comment by jeromeleecms** [comment]
Bill has been added to the new channel. Closing this out.
