### ISSUE TITLE
Do Some Tuts

### ISSUE THREAD

**Issue by cthulhuplus** [Enterprise-CMCS/eAPD#4393]
Do some  tutorials to familiarize yourself with Packer, CircleCI, AWS CLI, and Terraform. You can use either the free tier of AWS or the Fearless sandbox for these tutorials.

Packer: https://developer.hashicorp.com/packer/tutorials/aws-get-started (Install Packer through Variables)

CircleCI: https://circleci.com/docs/getting-started/ and https://circleci.com/docs/hello-world/

AWSCLI: https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html
https://docs.aws.amazon.com/cli/latest/userguide/cli-services-ec2-instances.html

Terraform: https://developer.hashicorp.com/terraform/tutorials/aws-get-started (What is Infrastructure as Code with Terraform through Define Input Variables)

### This task is done when...

- [ ] You've done the stuff
- [ ] We've discussed the tools and how we use them (again)

**Comment by cthulhuplus** [comment]
Hey @amyd11 I’m using Zenhub in GitHub, [click this link](https://app.zenhub.com/workspaces/cms-eapd-5a3823ad3659e94d8ee569be/board) to join my workspace and see other features available in GitHub or [download the Zenhub extension](https://www.zenhub.com/extension) and sign up with your GitHub account. 
  _Posted using [Zenhub](https://www.zenhub.com)_

**Comment by jeromeleecms** [comment]
This is no longer needed.
