### ISSUE TITLE
Documenting Product Process Ownership Changes

### ISSUE THREAD

**Issue by stephanieboydcms** [Enterprise-CMCS/eAPD#4396]
Creating an issue here to track the division of product duties since my onboarding between myself and Jerome. This issue will be considered complete when:

[ ] Document has been created that lists the changes and owner of product-related changes
[ ] Document has been reviewed, edited and approved by team
[ ] Process changes have been implemented
[Product Leadership Breakdown Draft.docx](https://github.com/Enterprise-CMCS/eAPD/files/9964147/Product.Leadership.Breakdown.Draft.docx)

**Comment by jeromeleecms** [comment]
This needs to have a final review and should be completed shortly.

**Comment by jeromeleecms** [comment]
OBE
