### ISSUE TITLE
Research Hosting Multiple API Versions 

### ISSUE THREAD

**Issue by cthulhuplus** [Enterprise-CMCS/eAPD#4399]
We need to be able to support multiple API versions in the future. A VERY brief look indicates there are multiple strategies to achieve this. We need to further research these options and choose a strategy.

### This task is done when...

- [ ] Research supporting multi API versions
- [ ] Present options to team
- [ ] Choose a strategy
- [ ] Create followup issues

**Comment by jeromeleecms** [comment]
Hey @yonassrobi I’m using Zenhub in GitHub, [click this link](https://app.zenhub.com/workspaces/cms-eapd-5a3823ad3659e94d8ee569be/board) to join my workspace and see other features available in GitHub or [download the Zenhub extension](https://www.zenhub.com/extension) and sign up with your GitHub account.
  _Posted using [Zenhub](https://www.zenhub.com)_

**Comment by jeromeleecms** [comment]
Research has been done as part of Greenfield analysis and actual work will be done in a separate ticket.
