### ISSUE TITLE
[Follow up] on paying for Chromatic

### ISSUE THREAD

**Issue by thetif** [Enterprise-CMCS/eAPD#4402]
When we linked our Chromatic account with our repo, we changed Chromatic groups. We lost our current payment set up, and now the payment for the whole org. 

### This task is done when...

- [ ] Jose has resolved how to pay for this
- [ ] Jose has determined how we will handle paying if another project joins our Chromatic org
- [x] If we are still paying, Jacques has moved the billing to the Enterprise-CMCS org
- [x] Chromatic has prorated our payment for the month we already paid

**Comment by jeromeleecms** [comment]
This is closed pending any new projects attempting to leverage Chromatic.
