### ISSUE TITLE
Write Comprehensive Tests for 4209

### ISSUE THREAD

**Issue by Sun-Mountain** [Enterprise-CMCS/eAPD#4403]
Because of the complicated nature of the `enableMmis` launch darkly flags, we are separating the tests from [#4209](https://app.zenhub.com/workspaces/cms-eapd-5a3823ad3659e94d8ee569be/issues/enterprise-cmcs/eapd/4209) to another ticket.

### This task is done when...

- [ ] All jest tests pass edge cases
- [ ] Launch darkly is set up in cypress to be used dynamically (This will be done in #4320)
- [ ] Cypress tests pass

---

Add additional labels (design, dev, compliance, BUG, etc) and size before
submitting.

If the issue is needed to complete prioritized work for the CURRENT SPRINT, add
it to the "This Sprint" pipeline. Otherwise, all other issues will be
automatically added to the _unprioritized pipeline_ for prioritization in
backlog refinement or sprint planning with Product.

**Comment by jeromeleecms** [comment]
@thetif Will verify which ticket from Quality is tied to this LD dynamic functioning and add the dependency here.
