### ISSUE TITLE
Address AWS Security Hub Findings

### ISSUE THREAD

**Issue by cthulhuplus** [Enterprise-CMCS/eAPD#4409]
Address new AWS Security Hub findings

### This task is done when...

- [ ] Unused EC2 security groups should be removed
- [ ] SNS topics should be encrypted at-rest using AWS KMS
- [ ] EC2 instances should be managed by AWS Systems Manager
- [ ] S3 access control lists (ACLs) should not be used to manage user access to buckets
- [ ] S3 buckets should require requests to use Secure Socket Layer
- [ ] EC2 instances should use Instance Metadata Service Version 2 (IMDSv2)
- [ ] AWS Config should be enabled

**Comment by jeromeleecms** [comment]
Dup #4467
