### ISSUE TITLE
[Security Vulnerability] Insecure Direct Object Reference in Role Update Feature

### ISSUE THREAD

**Issue by thetif** [Enterprise-CMCS/eAPD#4411]
### Description and related issues
There is an Insecure Direct Object Reference in the PATCH request to update other user's roles at "https://staging-eapd-api.cms.gov/states/mn/affiliations/97". There are two roles options that are shown in the drop-down menu, but by changing the role number in the PATCH request, the user is able to assign other roles, including Admin level roles.

This Insecure Direct Object Reference allows a user to assign other users roles outside of what the application appears to allow at the "https://staging-eapd.cms.gov/state-admin#active" URL, including Admin level roles. This compromises the Integrity of the application by potentially giving significantly more access and authorization to a user than what is intended.

### Acceptance criteria

| Given | When | Then |
| ----- | ---- | ---- |
| a State Admin | approving a User for a role that they are allowed to approve (State Staff, State Contractor) | the User is approved for the role |
| a State Admin | approving a User for a role that they are not allowed to approve (Sys Admin, State Admin, Federal Admin) | the User is not approved and not given a role and the attempt is logged in the audit table |
| a Federal Admin | approving a State Admin with a current State Approval Certificate | the State Admin is approved |
| a Fed Admin | approving a State Admin without a current State Approval Certificate | the State Admin is approved and the attempt is logged in the audit table |

### This task is done when…

- [ ] all acceptance criteria are met
- [ ] a Federal Admin user can only approve a State Admin and only if they have a current State Approval Certificate
- [ ] a State Admin user can only approve a State Staff or State Contractor for their state
- [ ] attempts to approve roles that a user does not have access to are logged to the affiliation_audit table

**Comment by tbolt** [comment]
Update:
New requirement- Verify that when a user is being assigned a state admin role they also have a connected auth letter
