### ISSUE TITLE
[Feature] Update Key State Personnel for MMIS

### ISSUE THREAD

**Issue by thetif** [Enterprise-CMCS/eAPD#4413]
### Description and related issues
MMIS APDs do not have a Program Administration activity where Key Personnel are added. For MMIS APDS ONLY, we will need to update the Key Personnel form.

1. The 3rd line in the Key Personnel and Program Management needs to be revised to say "Key personnel costs entered here are represented in the Proposed Budget, at the FFP specified below." (Proposed Budget is a hyperlink to the page)
2. The example box copy has changed,
3. The hint text for total has been added to explain the rationale behind the math. "Cost with benefits x FTE = Total"
4. An abridged Federal State Split is added to the subform that will appear if they select yes. There are only 2 options because Key State Personnel would likely only select funding at these match rates.
5. The validation would behave as usual with ffp being required if you say yes. The error message is "Select a federal-state split"
6. Update the Key State Personnel read-only component to display the fed-state split.

Update 1/18- New addition:
* For Key State Personnel we will need to collect the medicaid percentage contribution. For this we will have a new field where the percentage can be entered.

### Behind the scene changes:
* updating the MMIS schema to store the fed-state split for a Key State Personnel
* add set methods in actions/editAPD/keyPersonnel to handle saving the new fed-state split

### Mockups or link to Figma
https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=1901%3A15176
Design ticket: #2518

### Acceptance Criteria...

|Given|When|Then|
|---|---|---|
| an MMIS APD | adding a Key Personnel | the changes in the Figma will display | 
| an MMIS APD adding a Key Personnel | the form is invalid | the validation stays the same but requires the Fed-state split to be selected |
| a HITECH APD | adding a Key Personnel | the form will stay mostly the same but will add the hint for the total |
| a HITECH APD adding a Key Personnel | the form is invalid | the validation stays the same as it is now |
| a MMIS APD | on the Key Personnel subforum | If a key personnel has a cost, there should be another subforum asking for fed-state split. If the key personnel has no cost, the fed-state split subforum should not show |
| a Key Personnel | changing the fed-state split | the change is reflected throughout the APD |
| a MMIS APD| looking through help text on the Key Personnel page | 3rd list item of the description says "Key personnel costs entered here are represented in the Proposed Budget, at the FFP specified below." |  
| a MMIS APD | looking at the example below the description list | Example box says "Examples: Project/Product Manager, Development Lead, Business Owner" | 
| a MMIS APD | looking at the example below the description list | Example box says "Examples: Project/Product Manager, Development Lead, Business Owner" |
| a MMIS APD, Key state personnel page | changing the fed-state split | Schema is updated to save the fed-state split |
| a MMIS APD on the export page | A key personnel with a cost is entered | Read only view should show the fed-state split also |

### This task is done when…

**MMIS APDs ONLY**
- [x] 3rd list item of the description says "Key personnel costs entered here are represented in the Proposed Budget, at the FFP specified below."
- [x] Example box says "Examples: Project/Product Manager, Development Lead, Business Owner"
- [x] added an abridged Federal State Split to the Key Personnel form
- [x] added validation for the Federal State Split to sat "Select a federal-state split"
- [x] the schema has been updated to save the fed-state split
- [x] the Key State Personnel read-only component has been updated to display the fed-state split

**Both APD Types**
- [x] add the hint text "Cost with benefits x FTE = Total" underneath the total

**Comment by mirano-darren** [comment]
Acceptance criteria looks good to me! 👍

**Comment by jeromeleecms** [comment]
@mirano-darren Can you review the acceptance criteria <- -> this "task is done when?" And bring it into alignment as a single acceptance criteria table? I can work on it with you when you get back.

**Comment by akuas** [comment]
Looks good to me @thetif

**Comment by mirano-darren** [comment]
@jeromeleecms added some more test cases based on the This task is done when? section

**Comment by thetif** [comment]
@jeromeleecms @SGilliamA1M can I get sign off on this dev ticket?

**Comment by SGilliamA1M** [comment]
@thetif looks good to me!

**Comment by jeromeleecms** [comment]
this seems good -- thanks all!
