### ISSUE TITLE
AWSCLI Tutorials

### ISSUE THREAD

**Issue by cthulhuplus** [Enterprise-CMCS/eAPD#4426]
Do these two AWSCLI Tutorials:

https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html
https://docs.aws.amazon.com/cli/latest/userguide/cli-services-ec2-instances.html

### This task is done when...

- [ ] Getting Started/Install
- [ ] CLI Services - EC2 Instances

**Comment by jeromeleecms** [comment]
OBE
