### ISSUE TITLE
Terraform Tutorials

### ISSUE THREAD

**Issue by cthulhuplus** [Enterprise-CMCS/eAPD#4427]
Completed these Terraform tutorials:
https://developer.hashicorp.com/terraform/tutorials/aws-get-started

### This task is done when...

- [ ] What is Infrastructure as Code with Terraform?
- [ ] Install Terraform
- [ ] Build Infrastructure
- [ ] Change Infrastructure
- [ ] Destroy Infrastructure
- [ ] Define Input Variables

**Comment by jeromeleecms** [comment]
OBE
