### ISSUE TITLE
eAPD Confluence Space - Setup + Document Migration

### ISSUE THREAD

**Issue by SGilliamA1M** [Enterprise-CMCS/eAPD#4428]
Create a new eAPD Confluence space to house selective team documents, currently stored in Google Drive.

### This task is done when...

- [x] Designs are mocked up and shared with team for feedback and revisions
- [x] Designs are approved by team
- [x] Landing Page: Layout and Design has been implemented
- [x] Resources Directory: Background, Onboarding, and Disaster Recovery and Contingency Plans" - Layout and Design has been implemented
- [x] 508 Compliant

**Comment by SGilliamA1M** [comment]
@jeromeleecms @stephanieboydcms - our team Confluence Space + additional documents pertaining to product Background, Onboarding, Disaster Recovery and Team Calendars has been setup and ready for review.

**Comment by stephanieboydcms** [comment]
@SGilliamA1M, nothing additional besides Jerome's comment.  Good to move forward!

**Comment by jeromeleecms** [comment]
Done - we'll continue to update the pages as needed.
