### ISSUE TITLE
Review Project Brief 

### ISSUE THREAD

**Issue by yonassrobi** [Enterprise-CMCS/eAPD#4429]
### Mockups or link to Figma
Review the MAC-FC project brief confluence page and discuss project scope/priorities.

### Acceptance criteria

Di

| Given | When | Then |
| ----- | ---- | ---- |
|       |      |      |

### This task is done when…
Scope and priorities are discussed and action items are documented.

- [ ] all acceptance criteria are met
- [ ]

**Comment by jeromeleecms** [comment]
This is done; @yonassrobi has reviewed and ID'd items for completion
