### ISSUE TITLE
[Bug] Validation error messages on the Activity Overview page are incorrect on the MMIS APD seed

### ISSUE THREAD

**Issue by mirano-darren** [Enterprise-CMCS/eAPD#4444]
### Description
For the MMIS APD seed, the validation messages on the Activity Overview page are incorrect.
![image.png](https://images.zenhubusercontent.com/60e5e61f47c95c0dd8ed87be/93b34951-5731-427b-b959-771de9001ee6)

It should be:
![image.png](https://images.zenhubusercontent.com/60e5e61f47c95c0dd8ed87be/01d7d3a3-1a2f-4afc-8bdc-a32df2110e53)

### Steps to reproduce

1. Seed the database and go into the MMIS APD seed
2. Run admin check
3. Verify the validation error message for the mentioned activity overview fields have incorrect validation messages

**Expected results-**
Validation messages in the second pic

**Actual results-**
Validation messages in the first pic

### Role Affected

- [ ] All
- [ ] Federal Admin
- [x] State Admin
- [x] State Staff
- [x] State Contractor
- [ ] System Admin

### Environment

- [ ] All
- [ ] PR #\_\_\_\_
- [x] Staging
- [ ] Production

### Browser

- [ ] All
- [ ] Firefox
- [x] Chrome
- [ ] IE

**Comment by jeromeleecms** [comment]
@thetif @tbolt @amyd11 Will verify if this was already fixed in one of the PR's they are working on.

**Comment by mirano-darren** [comment]
fixed in #4415!
