### ISSUE TITLE
[Design] MMIS - MDBT Inclusion of D&O and M&O Costs for Executive Summary 

### ISSUE THREAD

**Issue by SGilliamA1M** [Enterprise-CMCS/eAPD#4450]
1. The MDBT (Medicaid Detailed Budget Table) inclusion for MMIS will be designed to support/have a designation for capturing DDI (Design Development & Installation funding) and M&O (Maintenance & Operations) Costs.
2. The [sample MDBT,](https://docs.google.com/spreadsheets/d/1y_25C-E9tBLhhiH-e0ZxkqSZBfY2oL_y/edit#gid=1171187501) will be visually translated and itemized to show the following:

- Proposed Budget Table -> DDI Costs Table
- Proposed Budget Table -> M&O Costs Table

3. The MDBT can span multiple federal fiscal years:
**MMIS DDI Costs**
- MMIS DDI (90/10)
- MMIS DDI (70/25)
- MMIS DDI (50/50)

**MMIS M&O Costs**
- MMIS M&O (75/25)
- MMIS M&O (50/50)

4. CMS Officer can approve 1yr (current) + 2nd yr, if the state provides enough justification and if their budget cycle will allow that. 

---

### This task is done when…

- [x] Feature Discovery Session is conducted with PM
- [x] Designs are created, taking into consideration validation, multiple FFY, multiple entries, long entries, weird entries, and/or the export view if applicable
- [x] Designs are annotated, capturing what has been added/changed, UI states and (if applicable) Feature Flag specifications
- [x] Any accessibility and acceptance criteria (not process oriented, requirements of feature)
- [x] 508 visual, content, and UX considerations and/or recommendations are reviewed
- [x] Designs are shared
- [ ] Designs are approved by Design Lead, Product, & Dev Lead
- [ ] If there is a long discussion, a summary of changes for dev will be added to the last comment before transfer
- [ ] a list of changes to be made if this is improving an existing feature

---

Add additional labels (design, dev, compliance, BUG, etc) and size before submitting.

If the issue is needed to complete prioritized work for the CURRENT SPRINT, add it to the "This Sprint" pipeline. Otherwise, all other issues will be automatically added to the _unprioritized pipeline_ for prioritization in backlog refinement or sprint planning with Product.

**Comment by SGilliamA1M** [comment]
@jeromeleecms and @stephanieboydcms - the Executive Summary is available for a final review. Please see updated designs here: https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=2663%3A17558&t=5f6USvbNWlqCGlL2-3. Thanks

**Comment by jeromeleecms** [comment]
Executive summary looks like it reflects what we talked about. Based on the designs/diiscussion from Akua, do we need to mock up a version to include what it looks like for 3 FFYs (she mentioned alternate striping for readability)?  Otherwise, this is looking good.

**Comment by SGilliamA1M** [comment]
Thanks @jeromeleecms! Alternate striping occurs when there are 5+ rows (will be specified in table redesign annotations) however I did include the updated background that highlights the "Total Computable Medicaid Cost" column. I've also annotated FFY expanding up to 3yrs. Please let me know if you have any further questions/concerns.

**Comment by thetif** [comment]
created ticket #[4474](https://app.zenhub.com/workspaces/cms-eapd-5a3823ad3659e94d8ee569be/issues/gh/enterprise-cmcs/eapd/4474)

**Comment by jeromeleecms** [comment]
Reviewed Dev Ticket, slight updates to the testing criteria, but closing this ticket as done and now pending dev.
