### ISSUE TITLE
[Maintenance] Audit yaml

### ISSUE THREAD

**Issue by thetif** [Enterprise-CMCS/eAPD#4453]
### Description and related issues

Look through the yaml code and note where it is used. Determine where it is best to use yaml. Look in the code and make sure that the existing components are using it correctly. Clean up any components that are using it wrong.

### This task is done when…

- [ ] a yaml standard has been determined
- [ ] the standard is documented
- [ ] yaml is being used consistently through out the applicaiton

**Comment by jeromeleecms** [comment]
closing this in favor of #2906
