### ISSUE TITLE
[Design] Product and Design Process Map

### ISSUE THREAD

**Issue by SGilliamA1M** [Enterprise-CMCS/eAPD#4457]
1. Make a visual diagram that illustrates the current procedure for implementing the product roadmap and design. 
2. Each time a process modification takes place, the visual diagram will be updated and used as a future reference. 
3. As part of onboarding, the eAPD team and new members will consult document to learn about internal procedures.

### This task is done when...

- [x] Visual documentation of the product process map
- [x] Visual documentation of the design process map
- [x] Shared with team for preliminary feedback/comments
- [ ] Product Approves document
- [ ] Document is housed in Confluence for team reference
---

Add additional labels (design, dev, compliance, BUG, etc) and size before
submitting.

If the issue is needed to complete prioritized work for the CURRENT SPRINT, add
it to the "This Sprint" pipeline. Otherwise, all other issues will be
automatically added to the _unprioritized pipeline_ for prioritization in
backlog refinement or sprint planning with Product.

**Comment by SGilliamA1M** [comment]
@jeromeleecms and @stephanieboydcms - changes didn't seem to save in Github for revised process documentation. :( Will try again today and follow-up once it's available!

**Comment by SGilliamA1M** [comment]
@jeromeleecms and @stephanieboydcms the Product and Design Process Maps have been added to our [Workflow and Processes Wiki](https://github.com/Enterprise-CMCS/eAPD/wiki/Workflows-and-processes) page. Please review when you have an opportunity. 

- [Design Process Map](https://github.com/Enterprise-CMCS/eAPD/wiki/Workflows-and-processes#handing-tasks-off-to-another-teammate) has been added (includes feedback from team)
- [Product Process Map](https://github.com/Enterprise-CMCS/eAPD/wiki/Workflows-and-processes#project-management) has been added (includes feedback from team)

**Comment by SGilliamA1M** [comment]
@jeromeleecms and @stephanieboydcms, I applied the following changes to reflect the latest feedback:

**Design Process Map**
1. Replaced Software Quality Tester with Quality Assignee
2. Updated final step in contextual process to account for Product Owners performing a final check prior to closing out Design ticket. Step 7, is shown as follows: "Product Owners ensure Development ticket and Testing Criteria is correct; Once Approved, Product Owners close original design ticket"

**Product Process Map**
1. Removed "Cake Layer Roadmap" and replaced with Roadmap
2. Removed spelling errors

**Comment by jeromeleecms** [comment]
Great - no additional comments. I'm good closing pending @stephanieboydcms reviews.

**Comment by stephanieboydcms** [comment]
This looks good to me as well.  Great job @SGilliamA1M !!!

**Comment by jeromeleecms** [comment]
This is done - until the next revisions.
