### ISSUE TITLE
[Design Issue] Add MDBT data to MMIS Proposed Budget

### ISSUE THREAD

**Issue by akuas** [Enterprise-CMCS/eAPD#4459]
This ticket breaks up the work in #4222, separating the Executive Summary work from the Proposed Budget.
Need to change the Combined Activity Costs and Summary Budget tables to include various match rates for MMIS

### This task is done when…

- [x] redesign Combined Activity Costs
- [x] redesign Summary Budget Table
- [x] designs are created, taking into consideration validation, multiple FFY,
      multiple entries, long entries, weird entries, and/or the export view if
      applicable
- [x] 508 visual, content, and UX considerations and/or recommendations are
      reviewed
- [x] designs are shared
- [x] closing notes are written
- [ ] designs are approved by product
- [ ] if there is a long discussion, a summary of changes for dev will be added
      to the last comment before transfer
- [ ] a list of changes to be made if this is improving an existing feature

---

Add additional labels (design, dev, compliance, BUG, etc) and size before
submitting.

If the issue is needed to complete prioritized work for the CURRENT SPRINT, add
it to the "This Sprint" pipeline. Otherwise, all other issues will be
automatically added to the _unprioritized pipeline_ for prioritization in
backlog refinement or sprint planning with Product.

**Comment by akuas** [comment]
Notes on Proposed Budget from a couple of weeks agao
1. CMS want to see the wrap up of different funding sources (DDI, M&O, and Other Payers)
2. Differs from HITECG because in HITECH the assumption was all costs were DDI
3. The 1st and 3rd table needs to change and will likely result in more tables for the Summary Budget Table section
4. CMS wants to trace the funding at every match rate and the design should be flexible enough to allow for more payers in E&E
5. For the summary budget table, we would want a summary by DDI/M&O not FFY
6. We are more concerned with Medicaid costs

**Comment by akuas** [comment]
@jeromeleecms Can you please take a look at the Combined Activity Costs table and let me know if this is what you were imagining? Also, please disregard the rest. Im creating a current and future enhancement version of this page, so for the future enhancement there wouldn't be an APD Budget Highlights, also not done with the Summary Budget Table yet.
https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=2828%3A17377&t=vMVEkMPoYR03RJ1K-1

**Comment by jeromeleecms** [comment]
Added some comments, let me know if you want to review/talk through any of them.

**Comment by akuas** [comment]
@jeromeleecms Thanks for the comments. Can you please review this screen below instead. It would be the current design and the previous would be a future enhancement that Im still playing around with. While working on this I realized there are some things I need to change with the table redesign, namely alignment. While reading table design guidelines online, I learned that numbers should be right-aligned and text data should be left aligned. However, I don't love how that looks for the medicaid total computable because it spacing out the rows quite a bit, but I will address that in the table design ticket. 
As for the summary budget table, I understand organizing by funding source. But I was playing around with how the experience is in staging and find it hard to imagine a situation where one ffy would differ from the next because in the activities, we don't ask users to specify again what ffy do these costs (state personnel etc) pertain to. So, Im thinking the only difference would be by funding source and activity, not ffy. I know we talked about this before, but it is still a bit confusing. 
https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=3105%3A18647&t=YMDpC4lVnh9FpuqF-1

**Comment by akuas** [comment]
@stephanieboydcms Can you please review the help text as well. I need to figure out a way to present the information in the Summary budget table not in a personal voice. Also please let me know if you feel that some of the help text is not needed. 
https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=3105%3A18647&t=YMDpC4lVnh9FpuqF-1

**Comment by stephanieboydcms** [comment]
Very minor edit suggestions on wordage.  Great job Akua!

**Comment by jeromeleecms** [comment]
Looks good @akuas. @SGilliamA1M any final comments before transitioning this to @thetif?

**Comment by SGilliamA1M** [comment]
@akuas the Proposed Budget changes look great! @jeromeleecms - this is good to transition to @thetif

**Comment by thetif** [comment]
@akuas for the Combined Activity Costs does that table also contain the M&O costs?

**Comment by thetif** [comment]
created dev ticket #4450

**Comment by jeromeleecms** [comment]
@mirano-darren Did you look at this one yet? The ticket is not #4450, it's #4500. I see a testing table, but it's not completed.
