### ISSUE TITLE
[User Research] User Testing and Research Planning for MMIS Pilot

### ISSUE THREAD

**Issue by SGilliamA1M** [Enterprise-CMCS/eAPD#4465]
Itemize and confirm Research Planning document for MMIS Pilot.

1. Confirm user grp(s) and total for User Testing session
2. Confirm recruiting method, date, and time of User Testing session
3. Confirm hypothesis-driven questionnaire 
4. Collaborate with HCD Unification contact for Research assistance

### This task is done when...

- [x] Research Planning Document is shared with team for preliminary feedback
- [ ] Product has reviewed and approved document in Confluence

---

Add additional labels (design, dev, compliance, BUG, etc) and size before
submitting.

If the issue is needed to complete prioritized work for the CURRENT SPRINT, add
it to the "This Sprint" pipeline. Otherwise, all other issues will be
automatically added to the _unprioritized pipeline_ for prioritization in
backlog refinement or sprint planning with Product.

**Comment by jeromeleecms** [comment]
This is done!
