### ISSUE TITLE
CircleCI Security Breach

### ISSUE THREAD

**Issue by cthulhuplus** [Enterprise-CMCS/eAPD#4468]
CircleCI has announced a security breach and so we have declared a security incident. 

### This task is done when...

- [ ] Security Incident is declared over

**Comment by cthulhuplus** [comment]
Created this Jira issue to rotate Slack Webhook
https://jira.cms.gov/browse/WHSD-49113

**Comment by cthulhuplus** [comment]
Waiting on the potentially exposed New Relic license to be terminated. I have created a new one, that we are using, but the previous one is still around, I am unable to delete it myself.

**Comment by jeromeleecms** [comment]
Still waiting for the CMS team to tell us whether or not this is done at the CMS level + to update our internal documentation.

**Comment by jeromeleecms** [comment]
Still waiting for CMS team to confirm.
