### ISSUE TITLE
[Testing] Cypress fixtures refactor for MMIS tests

### ISSUE THREAD

**Issue by mirano-darren** [Enterprise-CMCS/eAPD#4469]
Describe the task here and link or add dependencies to any applicable issues...

Create the Cypress fixtures for the upcoming MMIS tests. These should have the same format as the APD object in /api/seeds/development/

### This task is done when...

- [ ] fixture for MMIS cypress tests have been created 
- [ ] update any existing MMIS cypress test to use variables from this fixture file

**Comment by mirano-darren** [comment]
Holding off on merging this until #3698 is merged into main since that upgrades Cypress to version 12. Want to avoid giving Tif merge conflicts :)

**Comment by jeromeleecms** [comment]
This is done - #4447 was merged
