### ISSUE TITLE
Dashboard Inventory and Overview

### ISSUE THREAD

**Issue by cthulhuplus** [Enterprise-CMCS/eAPD#4470]
We have a number of dashboards that we use to monitor the eAPD. To help improve awareness around the purpose and types of dashboards that are available, we should inventory the dashboards and answer some basic questions around them:

1) What is it's name?
2) What is it used for?
3) Who should have access to it?
4) Where is it located?
5) When would I need to use it?
6) There may be a How to use it in here, but outside of the scope of the inventory.

Maybe some other things? 

### This task is done when...

- [ ] Inventory of Dashboards is complete with the criteria listed above in Mural
- [ ] Inventory posted in Confluence
- [ ] Team has had a walkthrough of the inventory

**Comment by jeromeleecms** [comment]
This is wrapping up with the project.
