### ISSUE TITLE
[Feature] Executive Summary update for MMIS

### ISSUE THREAD

**Issue by thetif** [Enterprise-CMCS/eAPD#4474]
### Description and related issues
Update the Program Budget Tables for MMIS to display the MMIS DDI Costs and MMIS M&O Costs tables.

### Mockups or link to Figma
Design #4450
https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=2663%3A17558&t=5f6USvbNWlqCGlL2-3

### Behind the scene changes
The Budget Calculations will have to be updated to calculate the values for the MMIS DDI costs and MMIS M&O costs. The MMIS Budget model will need to be updated to store the new calculations. Sum costs by Category/MMIS DDI and M&O by split type/FFY; see sumMMISbyFFP for an example of how to do this. If all of the costs in the MMIS M&O Costs or MMIS DDI Costs table are $0, then hide the table. 

### Acceptance criteria

- [x] Add the tables to the Program Budget Table
- [x] the M&O table is hidden if all of its values are $0
- [x] the DDI table is hidden if all of it's values are $0

### Testing criteria

| Given | When | Then | Covered |
| ----- | ---- | ---- | ------- |
|A MMIS APD|On the Executive Summary Page|MMIS DDI costs and M&O costs table are present|(Add a checkmark here when covered)|
|A MMIS APD|On the Executive Summary Page, Funding percentage is changed|Tables should be updated according to the change |  |
|A MMIS APD|On the Executive Summary Page|If there is 0 M&O Costs for all FFY, the M&O table should be hidden|  |
|A MMIS APD|On the Executive Summary Page|If there is 0 DDI Costs for all FFY, the DDI Table should be hidden|  |
|A MMIS APD|On the Executive Summary Page|Page accounts for APDs with zero activities|  |
|A MMIS/HITECH APD|On the Executive Summary Page|If a FFY is deleted, that year is removed from each section and the budget tables. NOTE: Possibly not testable since we can't delete FFYs in MMIS APDs yet |  |
|A MMIS/HITECH APD|On the Executive Summary Page|If a FFY is added, that year is added to each section and the budget tables.  |  |
|A HITECH APD|On the Executive Summary page|DDI and M&O cost tables should not appear| |

**Comment by jeromeleecms** [comment]
Updated/Added some testing criteria. @mirano-darren feel free to revise/update to align with any standard form that you might use. Closing the design ticket.

**Comment by mirano-darren** [comment]
Merging this in after #4500 gets merged in
