### ISSUE TITLE
eAPD Budget Table FY23

### ISSUE THREAD

**Issue by stephanieboydcms** [Enterprise-CMCS/eAPD#4480]
We have been assigned a task of fulfilling the budget tables for our project under the MACPro family.  I am working with Egosha to complete the task.  

### This task is done when...

- [ ] Materials gathered to update the table
- [ ] Informing Sabrina when we are ready to update the table, as it covers the whole MACPro suite
- [ ] Information is submitted into the budget table
---

**Comment by stephanieboydcms** [comment]
I have the formula calculations ready to insert once Nichole and Michelle send me the usage numbers.  Meeting is 01.30.23

**Comment by jeromeleecms** [comment]
This portion of the work has been completed by @stephanieboydcms. More to follow if needed.
