### ISSUE TITLE
Create Confluence Demo for MACBIS Team

### ISSUE THREAD

**Issue by SGilliamA1M** [Enterprise-CMCS/eAPD#4487]
Create a demo/tutorial that'll simply explain how to implement Confluence pages using CMS approved macros and CSS.

### This task is done when...

- [ ] PPT document detailing steps for setting up and creating Confluence pages

---

Add additional labels (design, dev, compliance, BUG, etc) and size before
submitting.

If the issue is needed to complete prioritized work for the CURRENT SPRINT, add
it to the "This Sprint" pipeline. Otherwise, all other issues will be
automatically added to the _unprioritized pipeline_ for prioritization in
backlog refinement or sprint planning with Product.

**Comment by SGilliamA1M** [comment]
@jeromeleecms - this ticket has been completed and can be closed out. Thanks!

**Comment by jeromeleecms** [comment]
Nice work!
