### ISSUE TITLE
[Design Issue] Design Read Only Views for Select MMIS Pages

### ISSUE THREAD

**Issue by akuas** [Enterprise-CMCS/eAPD#4488]
Dev needs read only views, mainly for pages with subforms. 
List of requested read only views are on the bottom of the  [MMIS Changes](https://docs.google.com/spreadsheets/d/1yCB-XfLO6QJL4iugFhoUHZWYJZ7IMtwBI8ZgtVilHmE/edit?usp=sharing) pages

### This task is done when…

- [x] Design Key State Personnel read-only view
- [x] Design Activity Schedule and Milestones read-only view
- [x] Design State Staff and Expenses read-only view
- [x] Design Cost Allocation and Other Funding read-only view
- [x] Design Budget and FFP read only view
- [x] Design Proposed Budget read only view
- [x] designs are created, taking into consideration validation, multiple FFY,
      multiple entries, long entries, weird entries, and/or the export view if
      applicable
- [x] 508 visual, content, and UX considerations and/or recommendations are
      reviewed
- [x] designs are shared
- [x] designs are approved by product
- [x] if there is a long discussion, a summary of changes for dev will be added
      to the last comment before transfer
- [x] a list of changes to be made if this is improving an existing feature

---

**Comment by akuas** [comment]
@SGilliamA1M @jeromeleecms @stephanieboydcms This ticket is ready for review. The design is the same as the export view. The only change I've made was to revise the empty state in the proposed budget and add more annotations to the pages. 

https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=3867%3A27422&t=uo08wzbmi8Uxnvfg-1

**Comment by jeromeleecms** [comment]
As noted, this mirrors the export view for items with subforms. Just one comment about including pages that aren't present - but if we use the export view as a reference for the read only view which don't exist, this works for me.

**Comment by akuas** [comment]
@jeromeleecms Yes, the export view can be used as a complete reference since they are the same. So, the alt considerations and risks doesn't need to be added to this chunk of work.

**Comment by jeromeleecms** [comment]
Thanks @akuas! I'll await additional comments from @SGilliamA1M and @stephanieboydcms before doing anything additional on this.

**Comment by SGilliamA1M** [comment]
@jeromeleecms - changes look good, no further comments on my end. Great work @akuas

**Comment by stephanieboydcms** [comment]
Great job @akuas !  No additional comments.

**Comment by akuas** [comment]
@SGilliamA1M @stephanieboydcms Thanks for the review. @jeromeleecms This ticket is ready for dev :)

**Comment by thetif** [comment]
created dev tickets
* #4553
* #4554
* #4555
* #4556
* #4557
* #4558
* #4559
* #4560
* #4561

**Comment by akuas** [comment]
@jeromeleecms Below is the my list of outstanding copy changes. It is titled outstanding MMIS help text changes on the bottom right of the page. Let me know if I have missed any. In the meantime, I will start changing the designs. Also, you use have copy recommendations, you can either put a sticky beside the table of enter it into the table.
https://app.mural.co/t/ccs9461/m/cmsmural6360/1611780005309/48a85b47f678d3fd5858070e25da7025d2da0a09?sender=u78eaeef0ed599cf016d95977

**Comment by jeromeleecms** [comment]
@SGilliamA1M Any concerns with the new dev tickets? Some of them are already closed out and if the rest are closed, we can close this ticket out.

**Comment by SGilliamA1M** [comment]
@jeromeleecms - dev tickets capture screens needed for read-only view. A few tickets still remain open.

**Comment by jeromeleecms** [comment]
Good to close.
