### ISSUE TITLE
Close Button on the Temporary Message should read "Close Alert" instead of "Button"

### ISSUE THREAD

**Issue by jeromeleecms** [Enterprise-CMCS/eAPD#4494]
### Description

After speaking with @akuas, the "X" button should read as an action, not simply as "button" to help users know what the button does.

![image](https://user-images.githubusercontent.com/34279968/214685836-b8e65b2c-0a47-4c7a-930f-5801c9fade22.png)

### Steps to reproduce

1. Create a new APD
2. Have the screen reader read the button
3. The screen reader will read "button"

### Role Affected

- [ ] All
- [ ] Federal Admin
- [X] State Admin
- [X] State Staff
- [X] State Contractor
- [X] System Admin

### Environment

- [X] All
- [ ] PR #\_\_\_\_
- [ ] Staging
- [ ] Production

### Browser

- [X] All
- [ ] Firefox
- [ ] Chrome
- [ ] IE

**Cypress test created OR Ticket for cypress test created-**

**Related user story/bug-** (if applicable)

#4441

**Comment by SGilliamA1M** [comment]
Looks like the "aria-label" within the HTML will need to be modified from reading as "button" to "Close Alert".

**Comment by jeromeleecms** [comment]
This will be fixed in #4354 - closing this one.
