### ISSUE TITLE
Greenfield migration planning

### ISSUE THREAD

**Issue by yonassrobi** [Enterprise-CMCS/eAPD#4496]

**Comment by jeromeleecms** [comment]
Just some notes for planning work:

1) Confirmation of Budget, Approval, Running Side by Side for Legacy Environment Cost implications
2) Assessing cost changes with Atlas Mongo (if approved for use)
3) Assess implications for ATO status for new environments

**Comment by jeromeleecms** [comment]
Still working with DIS leadership for guidance for if/how to move forward on this.

**Comment by jeromeleecms** [comment]
Plan has been shared with @cthulhuplus. Will post in Google Drive or Confluence - TBD.
