### ISSUE TITLE
[Feature] Help Text Changes for Key Personnel and Program Management

### ISSUE THREAD

**Issue by thetif** [Enterprise-CMCS/eAPD#4508]
### Description and related issues
Based on design ticket #4381 

### Mockups or link to Figma
https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=3328%3A18573&t=VXupikAaT7lnGE7V-1

![Key Personnel and Program Management](https://user-images.githubusercontent.com/62778/216174372-bc031d5a-c0a6-4752-b6b3-bb3c58b9c256.png)

### Acceptance criteria

- [ ] change the 3rd list item in the description to 
> Key personnel costs entered here are represented in the Proposed Budget page, at the FFP specific below.
- [ ] change the example box to
> **Examples:** Project/Product Manager, Development Lead, Business Owner

**Comment by mirano-darren** [comment]
Ty already merged in these changes!
