### ISSUE TITLE
[Design Issue] Results of Previous Activity, Add M&O at 75/25 FFP

### ISSUE THREAD

**Issue by jeromeleecms** [Enterprise-CMCS/eAPD#4524]
Reviewing #4488, we recognized that we left out a budget table for MMIS in the "Results of Previous Activities"

In the results of Previous Activity, we should have represented:

MMIS DDI at 90/10, 75/25
MMIS M&O at 72/25*, 50/50

This should be consistent with the table redesigns from #3380.

Export views for this additional table has already been created in #3693. 

Figma: https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=2779%3A17295&t=ic7dMVAN5MGIBnEf-0

@SGilliamA1M Can you take a look at this issue to see what else you would like to add here (+ update the acceptance criteria)?

### This task is done when…

- [x] 75/25 M&O table is added to Figma Design
- [x] Document any changes for the builder view
- [x] 508 visual, content, and UX considerations and/or recommendations are
      reviewed
- [x] designs are shared
- [x] designs are approved by product
- [ ] if there is a long discussion, a summary of changes for dev will be added
      to the last comment before transfer
- [ ] a list of changes to be made if this is improving an existing feature

**Comment by akuas** [comment]
@stephanieboydcms @stephanieboydcms Can you please review this design. The only change is adding the 75/25 match rate table to the results of previous activities. Like the ticket notes, the export is not a apart of this because I already made the change in the export view ticket.

**Comment by stephanieboydcms** [comment]
I reviewed the updates via FIGMA and this is good to proceed. Thanks @akuas !

**Comment by SGilliamA1M** [comment]
@akuas - changes look great! Thanks

**Comment by akuas** [comment]
@jeromeleecms Hi Jerome, this ticket is ready for dev.

**Comment by jeromeleecms** [comment]
Reassigning to Dev!

**Comment by thetif** [comment]
created development tickets #4570 and #4571

**Comment by jeromeleecms** [comment]
This is already being worked on by Dev. Closing.
