### ISSUE TITLE
[Maintenance] Fix codecov reporting issue on api unit tests

### ISSUE THREAD

**Issue by thetif** [Enterprise-CMCS/eAPD#4541]
### Description and related issues
The codecov is only reporting a single file on the api unit tests now. This needs to be fixed to appropriately display the coverage of all of the relevant files.

![CleanShot 2023-02-13 at 12.21.30.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/bac8c1c8-a57c-4d68-b679-7059ad12165d)

### This task is done when…

- [ ] api unit tests have the correct codecov report

**Comment by jeromeleecms** [comment]
This is done.
