### ISSUE TITLE
[Feature] Update Read-Only View for MMIS changes to Proposed Budget

### ISSUE THREAD

**Issue by thetif** [Enterprise-CMCS/eAPD#4556]
### Description and related issues
Update the Proposed Budget section of the export view to display the new tables.

**Data State changes:**
* Combined Activity Costs: Add match rate table headers to combined activity costs
* Combined Activity Costs: Add key state personnel
* Combined activity costs keep activity 1 total computable medicaid cost and total computable medicaid cost section
* State and Contractor Cost Breakdown: Add key state personnel and APD point of contact signifier to the 1st key personnel
* Make sure design reflects mmis update maintain total medicaid cost with federal and state share totals
* State and Contractor Cost: Add % to represent medicaid share in table calculation
* Summary Budget table: add match rate table headers
* Summary Budget table: only show user selected match rates, so if there is no 50/50, there will be no table for it
* Summary Budget Table: make sure it reflects mmis changes

**Empty State changes:**
* This design shows the empty state of the proposed budget
* At the bare minimum, the only data we have is the FFY and that if there are any costs but no match rate the default match rate is 0/100, with the state paying 100%
* If a match rate is specified, but the user did not select any cost related fields in the activity and key state personnel pages, we will list the match rates for Combined Activity > Costs and Summary Budget table with $0 cost throughout.

### Mockups or link to Figma
Data state - https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=4185%3A20105&t=irHudAE6PbwrblAu-1
Empty state - https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=4185%3A20513&t=irHudAE6PbwrblAu-1

### Acceptance criteria

- [ ] create stories for data and empty state
- [ ] update Proposed Budget read-only component to display differently for HITECH and MMIS
- [ ] create MMIS version of read-only component to match the figma

### Testing criteria

| Given | When | Then | Covered |
| ----- | ---- | ---- | ------- |
|a HITECH APD| On the export view | Proposed Budget section should be the same and not have any MMIS updates |         |
|a MMIS APD| On the export view (use Chromatic if page crashes) | Proposed Budget section should match the data in the Proposed Budget page |         |
|a MMIS APD| Proposed Budget data is changed (added costs/deleted costs/edited costs) | Proposed Budget section should match the changed data |        
|a MMIS APD| Proposed Budget data is blank | Proposed Budget section should match the empty state |

**Comment by tbolt** [comment]
Update 4/13 - Team decided to focus on the following items for this ticket:
1. Remove alert in export view (Medicaid Total Computable by FFY section)
2. Remove help text in export view (Medicaid Total Computable by Match Rate and Medicaid Total Computable by FFY sections)
