### ISSUE TITLE
[Feature] Update Read-Only View for MMIS changes to Executive Summary

### ISSUE THREAD

**Issue by thetif** [Enterprise-CMCS/eAPD#4558]
### Description and related issues
Update the Executive Summary of the export view to display the match the figma updates.

**Changes for Executive Summary:**
* The Executive Summary Section is unchanged.
* Activity list stays the same, except the paragraph intro comes from activity snapshot
* The Program Budget Tables changed to reflect table redesign.
* MMIS M&O not shown if there are no M&O activities

### Mockups or link to Figma

Data view - https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=3674%3A23279&t=RAQ43sFg8BtVc5qU-1
Empty view - https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=3725%3A25149&t=2Pbpmc5Nooy0Cy7r-1

### Acceptance criteria

- [ ] create stories for data and empty state
- [ ] update Executive Summary read-only component to display differently for HITECH and MMIS
- [ ] create MMIS version of read-only component to match the figma

### Testing criteria

| Given | When | Then | Covered |
| ----- | ---- | ---- | ------- |
|a HITECH APD| On the export view | Executive Summary section should be the same and not have any MMIS updates |         |
|a MMIS APD| On the export view (use Chromatic if page crashes) | Executive Summary section should match the data in the Executive Summary page |         |
|a MMIS APD| Executive Summary data is changed (added/deleted/edited) | Executive Summary section should match the changed data |        
|a MMIS APD| Executive Summary data is blank | Executive Summary section should match the empty state |

**Comment by amyd11** [comment]
Chromatic link (has changes to evaluate): https://www.chromatic.com/build?appId=61d5b948cf6f17003a12bf77&number=1456
