### ISSUE TITLE
[Feature] Update the Results of Previous Activities form for MMIS

### ISSUE THREAD

**Issue by thetif** [Enterprise-CMCS/eAPD#4570]
### Description and related issues
Update the Results of Previous Activities form to work for MMIS APDs. Existing tables should be replaced by tables for:
* MMIS Federal Share 90% FFP
    * MMIS DDI at 90% FFP
* MMIS Federal Share 75% FFP
    * MMIS DDI at 75% FFP
    * MMIS M&O at 75% FFP
* MMIS Federal Share 50% FFP
    * MMIS DDI at 50% FFP
    * MMIS M&O at 50% FFP
* Grand Totals: Federal MMIS

Previous Activities Summary stays the same as in HITECH. Form should not change for HITECH APDs.

### Mockups or link to Figma
Design ticket #4524
https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=970%3A11404&t=O4FuAThZ7GZWbPjf-1

### Behind the scene changes
Update the MMIS model to store values split up by DDI and M&O

```
{
  actualExpenditures: {
    type: Map,
    of: new mongoose.Schema({
      ddi: {
        50: {
          federalActual: {
            type: Number,
            default: 0
          },
          totalApproved: {
            type: Number,
            default: 0
          }
        },
        75: {
          federalActual: {
            type: Number,
            default: 0
          },
          totalApproved: {
            type: Number,
            default: 0
          }
        },
        90: {
          federalActual: {
            type: Number,
            default: 0
          },
          totalApproved: {
            type: Number,
            default: 0
          }
        }
      },
      mando: {
        50: {
          federalActual: {
            type: Number,
            default: 0
          },
          totalApproved: {
            type: Number,
            default: 0
          }
        },
        75: {
          federalActual: {
            type: Number,
            default: 0
          },
          totalApproved: {
            type: Number,
            default: 0
          }
        }
      }
    })
  }
}
```

Update the editApd actions to save values for the new table model and tables.

** Refactor opportunity**
There is probably a cleaner way to update these tables than to have a separate method for updating each type.

### Acceptance criteria

- [ ] update the MMIS model as stated above
- [ ] update the form to match the figma for MMIS
- [ ] create actions for saving the values in the fields

### Testing criteria

| Given | When | Then | Covered |
| ----- | ---- | ---- | ------- |
| A HITECH APD | On the Results of Previous Activities page | page should stay the same |         |
| A MMIS APD | On the Results of Previous Activities page | 75% and 50%  FFP should have M&O tables |         |
| A MMIS APD | On the Results of Previous Activities page | tables should have headers with funding type |         |
| A MMIS APD | On the Results of Previous Activities page | tables should show current FFY and previous 2 FFYs |         |
| A MMIS APD | On the Results of Previous Activities page | tables should calculate based on the correct FFP |         |
| A MMIS APD | On the Results of Previous Activities page, changing/adding/deleting values in the tables | values are saved|         |
| A MMIS APD | On the Results of Previous Activities page, changing/adding/deleting values in the tables | totals table below adapts to the change|         |

**Comment by jeromeleecms** [comment]
One minor change to acceptance criteria @mirano-darren. Pending thoughts from design.

**Comment by SGilliamA1M** [comment]
@jeromeleecms and @mirano-darren - testing criteria looks good! Thanks
