### ISSUE TITLE
[Feature] Display standard APD header on activities pages

### ISSUE THREAD

**Issue by thetif** [Enterprise-CMCS/eAPD#4597]
### Description and related issues
The APD header is not being shown on the activities pages, but it should be shown on those pages as well.

### Mockups or link to Figma
![CleanShot 2023-03-13 at 13.38.39.png](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/c5f947d8-e830-4cc0-bcea-c65f10110426)

### Acceptance criteria

- [x] the header displays on the activities pages

**Comment by stephanieboydcms** [comment]
@Sun-Mountain this looks good to me!
