### ISSUE TITLE
[Design Issue] Create Closing Notes and Error Messages for Alt Considerations and Risks and Conditions for Enhanced Funding

### ISSUE THREAD

**Issue by akuas** [Enterprise-CMCS/eAPD#4600]
The designs are done for these pages with the MES expansion, but we need closing notes, annotations, and error message designs for them as they transition to dev work

### This task is done when…

- [ ] any acceptance criteria (not process oriented, requirements of feature)
- [x] designs are created, taking into consideration validation, multiple FFY,
      multiple entries, long entries, weird entries, and/or the export view if
      applicable
- [x] 508 visual, content, and UX considerations and/or recommendations are
      reviewed
- [x] designs are shared
- [ ] designs are approved by product
- [ ] if there is a long discussion, a summary of changes for dev will be added
      to the last comment before transfer
- [ ] a list of changes to be made if this is improving an existing feature

---

Add additional labels (design, dev, compliance, BUG, etc) and size before
submitting.

If the issue is needed to complete prioritized work for the CURRENT SPRINT, add
it to the "This Sprint" pipeline. Otherwise, all other issues will be
automatically added to the _unprioritized pipeline_ for prioritization in
backlog refinement or sprint planning with Product.

**Comment by akuas** [comment]
## [Analysis of Alternatives and Risks Closing Notes ](https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=8%3A9073&t=nGJPGYo8G7Bju18z-1)
As of 3.14.2023

1. These are all new fields for MMIS. 
2. Validation: 
> This page is completely optional. This should allow users to enter in new substantive info if need be and keep it blank if any of these planning questions have not been reassessed. 
> So, there will be no error messages and it will not show up on the admin check.
3. The field titles are all title case in this situation because they are proper nouns.

**Comment by akuas** [comment]
@jeromeleecms Can you please post the links for the standards and conditions help and the 42 cfr 433.112?

**Comment by akuas** [comment]
@thetif Above are the closing notes and I created a validation design for the conditions for enhanced funding. Let me know if there are any questions :).

**Comment by jeromeleecms** [comment]
@akuas Are you referring to: https://www.ecfr.gov/current/title-42/chapter-IV/subchapter-C/part-433/subpart-C/section-433.112?

**Comment by akuas** [comment]
@jeromeleecms Thanks, I think so. Do you remember if we were using the same link for both the help drawer and the enhanced funding justification.

**Comment by thetif** [comment]
@akuas I'm working on the Analysis of Alternatives and Risks right now, does it have error messages? @jeromeleecms are those fields required?

**Comment by thetif** [comment]
@akuas could we put the nested section between yes and no? We can do it the other way, but the Design System component is set up to open whatever directly under the checkbox and it's done like that is most of the other places in the system.

**Comment by thetif** [comment]
created dev tickets #4612, #4613

**Comment by jeromeleecms** [comment]
This looks fine, pending final design review. If the help drawer concept is hard to implement/time consuming, we can just open the link to the eCFR like we've done in the past with other reg references.

**Comment by SGilliamA1M** [comment]
@jeromeleecms the design specs look good.

**Comment by thetif** [comment]
I created a help drawer, but it comes out of the side of the screen and not right under the link. I was going to let Akua and Sherry let me know if that was ok.

**Comment by jeromeleecms** [comment]
This is good to close!
