### ISSUE TITLE
[User Research] Configure Dovetail and Itemize Touch Points for MMIS Pilot - Usability Testing

### ISSUE THREAD

**Issue by SGilliamA1M** [Enterprise-CMCS/eAPD#4615]
Our Dovetail environment will need to be set up ahead of time in order to store recorded sessions and synthesize user feedback data. We'll also need to be able to list specific touch points for each task: 1) Creating an MMIS IAPD; and 2) Editing an MMIS IAPD.

- [x] Dovetail environment is properly setup for Q2 Usability Testing
- [x] Touch points have been defined for each task conducted during Usability Testing
- [x] Dovetail link shared with Product Owners and team for review/feedback
- [x] Confluence link shared with Product Owners and team for review/feedback

---

Add additional labels (design, dev, compliance, BUG, etc) and size before
submitting.

If the issue is needed to complete prioritized work for the CURRENT SPRINT, add
it to the "This Sprint" pipeline. Otherwise, all other issues will be
automatically added to the _unprioritized pipeline_ for prioritization in
backlog refinement or sprint planning with Product.

**Comment by SGilliamA1M** [comment]
@jeromeleecms and @stephanieboydcms - please access and review the following url pertaining to the environment setup for [Dovetail](https://macbis.dovetailapp.com/projects/1PxNK0ggf4xznGo2fSM7Nw/readme). This environment will serve as one of primary research and data feedback tools. As a team, we will reference this tool to view user recordings and track observational information captured during the MMIS IAPD Pilot test.

In addition, please access and review our [2023 Q2 | User Research and Insights Report](https://confluenceent.cms.gov/display/MPEA/eAPD+-+2023+Q2+%7C+User+Research+and+Insights+Report). This online reporting document will serve as the final synthesis report and made accessible to our core team.

**Comment by jeromeleecms** [comment]
This is done!
