### ISSUE TITLE
Update budget documentation after MMIS changes

### ISSUE THREAD

**Issue by amyd11** [Enterprise-CMCS/eAPD#4663]
With the recent budget work for MMIS, it could be valuable to create some developer documentation complementary to the existing docs and comments in code. This info could help lower the learning curve with tackling any budget work in the future or getting refreshed with budget work if the developer hasn't seen it in a while.

### This task is done when...

- [ ] Any relevant existing documentation is updated
- [ ] Any new documentation is added and linked to the ticket

**Comment by amyd11** [comment]
New page exists here: https://github.com/Enterprise-CMCS/eAPD/wiki/Budget-code

**Comment by thetif** [comment]
checked this out this morning, it looks great, thanks for writing this up
